### PR TITLE
Eeschema: Spice simulator chapter

### PR DESCRIPTION
**Pull request by orsonmmz**

### CODE REVIEW

**Comment by stambaughw** [comment]
This looks good to me.  If there are no objections, I will merge it.

**Comment by ciampix** [comment]
No objection at all, great!

**Comment by stambaughw** [comment]
Thanks Orson for documenting the spice simulator.

**Comment by orsonmmz** [comment]
No problem, I am happy to help. There are more and more questions regarding the simulator appearing, so hopefully the documentation will clear them up a bit.

**Pull request merged**
