### PR TITLE
Update Polish translation of KiCad Manuals

### PR DESCRIPTION
**Pull request by keruseykaryu**
- Update translation for main applications (100% translated at the moment),
- Add new screenshots (Some new dialogs and menus, Eeschema simulator),
- Remove unused CvPbc screenshots for legacy config dialogs,
- Update initial comments to keep actual date of translation and copyright notice.

### CODE REVIEW

**Comment by keruseykaryu** [comment]
Have no idea why Eeschema's PDF generation by Travis still cannot pass... :(

**Comment by keruseykaryu** [comment]
Output for command 
`dblatex -t pdf -p "/etc/asciidoc/dblatex/asciidoc-dblatex.xsl" -s "/etc/asciidoc/dblatex/asciidoc-dblatex.sty" -P latex.output.revhistory=0 -P doc.publisher.show=0 -s /home/kerusey/KiCad-dev/kicad-doc-work/CMakeSupport/pdf-cover-dblatex.sty -o /home/kerusey/KiCad-dev/kicad-doc-work/build/src/eeschema/pl/eeschema.pdf  "/home/kerusey/KiCad-dev/kicad-doc-work/build/src/eeschema/pl/eeschema.xml"`

```
Build the book set list...
Build the listings...
XSLT stylesheets DocBook - LaTeX 2e (0.3.7-1)
===================================================
Build eeschema.pdf
pdflatex failed
eeschema.tex:278: Missing $ inserted.
eeschema.tex:278: leading text: ...atkowo jeden z klawiszy "SHIFT", "CTRL" l
eeschema.tex:281: Missing $ inserted.
eeschema.tex:3294: Argument of \language@active@arg" has an extra }.
eeschema.tex:3294: leading text: ...subsection{Flaga "Nie po\l{}\k{a}czone"}
eeschema.tex:3294: Paragraph ended before \language@active@arg" was complete.
eeschema.tex:3294: leading text: ...subsection{Flaga "Nie po\l{}\k{a}czone"}
eeschema.tex:3294: Paragraph ended before \HyPsd@@ProtectSpacesFi was complete.
eeschema.tex:3294: leading text: ...subsection{Flaga "Nie po\l{}\k{a}czone"}
eeschema.tex:3294: Use of \HyPsd@RemoveMask doesn't match its definition.
eeschema.tex:3294: leading text: ...subsection{Flaga "Nie po\l{}\k{a}czone"}
eeschema.tex:3294: Undefined control sequence \HyPsd@End.
eeschema.tex:3294: leading text: ...subsection{Flaga "Nie po\l{}\k{a}czone"}
eeschema.tex:3294: Paragraph ended before \HyPsd@RemoveBraces was complete.
eeschema.tex:3294: leading text: ...subsection{Flaga "Nie po\l{}\k{a}czone"}
eeschema.tex:3294: Argument of \HyPsd@CheckCatcodes has an extra }.
eeschema.tex:3294: leading text: ...subsection{Flaga "Nie po\l{}\k{a}czone"}
eeschema.tex:3294: Paragraph ended before \HyPsd@CheckCatcodes was complete.
eeschema.tex:3294: leading text: ...subsection{Flaga "Nie po\l{}\k{a}czone"}
eeschema.tex:3294: Paragraph ended before \HyPsd@RemoveMask was complete.
eeschema.tex:3294: leading text: ...subsection{Flaga "Nie po\l{}\k{a}czone"}
eeschema.tex:3294: Missing number, treated as zero.
eeschema.tex:3294: leading text: ...subsection{Flaga "Nie po\l{}\k{a}czone"}
eeschema.tex:3294: Illegal unit of measure (pt inserted).
eeschema.tex:3294: leading text: ...subsection{Flaga "Nie po\l{}\k{a}czone"}
eeschema.tex:3301: Missing { inserted.
eeschema.tex:3301: leading text: J
eeschema.tex:3301: Missing number, treated as zero.
eeschema.tex:3301: leading text: J
eeschema.tex:3301: Illegal unit of measure (pt inserted).
eeschema.tex:3301: leading text: J
eeschema.tex:3301: Missing number, treated as zero.
eeschema.tex:3301: leading text: J
eeschema.tex:3301: Illegal unit of measure (pt inserted).
eeschema.tex:3301: leading text: J
eeschema.tex:3301: Missing number, treated as zero.
eeschema.tex:3301: leading text: J
eeschema.tex:3301: Illegal unit of measure (pt inserted).
eeschema.tex:3301: leading text: J
eeschema.tex:3301: Missing { inserted.
eeschema.tex:3301: leading text: J
eeschema.tex:3301: Missing number, treated as zero.
eeschema.tex:3301: leading text: J
eeschema.tex:3301: Illegal unit of measure (pt inserted).
eeschema.tex:3301: leading text: J
eeschema.tex:3301: Missing number, treated as zero.
eeschema.tex:3301: leading text: J
eeschema.tex:3301: Illegal unit of measure (pt inserted).
eeschema.tex:3301: leading text: J
eeschema.tex:3301: Missing number, treated as zero.
eeschema.tex:3301: leading text: J
eeschema.tex:3301: Illegal unit of measure (pt inserted).
eeschema.tex:3301: leading text: J
eeschema.tex:3303: Illegal unit of measure (pt inserted).
eeschema.tex:3303: leading text: ...conn.png}}}}{Ikona Nie po\l{}\k{a}czone}
eeschema.tex:3303: Illegal unit of measure (pt inserted).
eeschema.tex:3303: leading text: ...conn.png}}}}{Ikona Nie po\l{}\k{a}czone}
eeschema.tex:3314: Illegal unit of measure (pt inserted).
eeschema.tex:3314: leading text: ...cons/text.png}}}}{images/icons/text.png}
eeschema.tex:3314: Illegal unit of measure (pt inserted).
eeschema.tex:3314: leading text: ...cons/text.png}}}}{images/icons/text.png}
eeschema.tex:3315: Illegal unit of measure (pt inserted).
eeschema.tex:3315: leading text: ...}}}}{images/icons/add\_dashed\_line.png}
eeschema.tex:3315: Illegal unit of measure (pt inserted).
eeschema.tex:3315: leading text: ...}}}}{images/icons/add\_dashed\_line.png}
eeschema.tex:3315: Missing $ inserted.
eeschema.tex:3315: leading text: ...}}}}{images/icons/add\_dashed\_line.png}
eeschema.tex:3315: Extra }, or forgotten $.
eeschema.tex:3315: leading text: ...}}}}{images/icons/add\_dashed\_line.png}
eeschema.tex:3315: Extra }, or forgotten $.
eeschema.tex:3315: leading text: ...}}}}{images/icons/add\_dashed\_line.png}
eeschema.tex:3315: Extra }, or forgotten $.
eeschema.tex:3315: leading text: ...}}}}{images/icons/add\_dashed\_line.png}
eeschema.tex:3315: Missing $ inserted.
eeschema.tex:3315: leading text: ...}}}}{images/icons/add\_dashed\_line.png}
eeschema.tex:3315: Missing } inserted.
eeschema.tex:3315: leading text: ...}}}}{images/icons/add\_dashed\_line.png}
eeschema.tex:3315: Missing } inserted.
eeschema.tex:3315: leading text: ...}}}}{images/icons/add\_dashed\_line.png}
eeschema.tex:3315: Missing } inserted.
eeschema.tex:3315: leading text: ...}}}}{images/icons/add\_dashed\_line.png}
eeschema.tex:3321: Use of \begin doesn't match its definition.
eeschema.tex:3321: leading text: \begin{
eeschema.tex:3321: Missing number, treated as zero.
eeschema.tex:3321: leading text: \begin{center}
eeschema.tex:3321: Illegal unit of measure (pt inserted).
eeschema.tex:3321: leading text: \begin{center}
eeschema.tex:3321: Infinite glue shrinkage found in a paragraph.
eeschema.tex:3321: leading text: \begin{center}
eeschema.tex:3321: Missing number, treated as zero.
eeschema.tex:3321: leading text: \begin{center}
eeschema.tex:3321: Illegal unit of measure (pt inserted).
eeschema.tex:3321: leading text: \begin{center}
eeschema.tex:3321: Infinite glue shrinkage found in a paragraph.
eeschema.tex:3321: leading text: \begin{center}
eeschema.tex:3323: Use of \begin doesn't match its definition.
eeschema.tex:3323: leading text: \noindent\begin{
eeschema.tex:3323: Unbalanced output routine.
eeschema.tex:3323: leading text: \noindent\begin{minipage}
eeschema.tex: Emergency stop.

A possible reason for transformation failure is invalid DocBook
(as reported by xmllint)

Error: pdflatex compilation failed
```

I've tried to change `:doctype:` from `book` to `article` (Only Eeschema has a `book`). No luck.

**Comment by ciampix** [comment]
Sorry, was busy with real world work, I'll see it this afternoon (hope)

**Comment by ciampix** [comment]
Seems that travis is hanging... never mind I'll merge it anyway and is there will be issues I'll see to them ASAP...

**Comment by keruseykaryu** [comment]
I think there will be no problem now. I've successfully build PDF and HTML (Polish only).

_ps. My env has a problem to build all languages anyway. :(_

**Comment by ciampix** [comment]
No problem. I was confident that it was ok or at least I would be able to figure out any problem that could have been surfaced during compilation time, so I proceeded to merge it. Then I compiled on my laptop and there were no problems at all. See my last comment on issue #638 ...

**Comment by keruseykaryu** [comment]
So. **Big thanks for your abnormal efforts to solve this**. 
See you when 6.0 will be released. Unless someone else "step into the breach" with Polish translations.

**Pull request merged**
