### PR TITLE
[CvPcb] Russian translation corrected to latest updates.

### PR DESCRIPTION
**Pull request by baranovskiykonstantin**

### CODE REVIEW

**Comment by nickoe** [comment]
I suspect that you did not intend to close this issue? Closing it does not mean that it is merged.

**Comment by baranovskiykonstantin** [comment]
@nickoe, russian translations of Eeschema manual must be pulled first. Then I will reopen this pull request. I am hurried, sorry about that.

**Comment by nickoe** [comment]
Ok.

**Comment by nickoe** [comment]
I merged the eeschema pull request, but it seems like this pull request is still conflicting?

**Comment by baranovskiykonstantin** [comment]
I was afraid of that.
Now all must be fine.

**Pull request merged**
