### PR TITLE
KiCad-doc Simplified Chinese updated to v0.3

### PR DESCRIPTION
**Pull request by taotieren**

### CODE REVIEW

**Comment by ciampix** [comment]
Thanks!

**Comment by taotieren** [comment]
@ciampix thanks

**Comment by taotieren** [comment]
http://docs.kicad-pcb.org/master/zh/

How often is this documentation website updated? The content inside is still relatively long.

**Comment by ciampix** [comment]
What do you mean? I mean what worries you?

**Comment by taotieren** [comment]
No, I mean this document site is not updated in real time, how long is the update cycle of this document site.（http://docs.kicad-pcb.org/master/）

**Comment by nickoe** [comment]
It usually takes about 35 minutes to build the docs, and there is a sync latency of about 15 minutes to publish the docker image. So usually it is updated after 1 hour.

**Comment by taotieren** [comment]
@nickoe I have merged the Chinese translation I submitted. Why does the master branch on the documentation website still display the old document content?

**Comment by nickoe** [comment]
Remember to select the correct version in the top right corner.

**Comment by nickoe** [comment]
@taotieren If you still think something is missing, please point out a section where I can see if it is updated or not and I can investigate the logs. I am not well versed in Chinese.

**Comment by taotieren** [comment]
I mean, after my translation, the document website hasn't been updated to the content of my latest translation or the old one.The Chinese documents on the document website haven't been updated for a long time.

**Comment by taotieren** [comment]
There are still no Chinese help documents in the latest nighttime version.

**Comment by taotieren** [comment]
And help documentation is not optional when installing.

**Pull request merged**
