### PR TITLE
Add support for selecting multiple languages

### PR DESCRIPTION
**Pull request by StefanBruens**
Previously, either all available languages could be built, or a single
language could be selected using e.g. -DSINGLE_LANGUAGE=de. Add LANGUAGES,
which accepts a list of languages, e.g. -DLANGUAGES=en;de;fr.
SINGLE_LANGUAGE is kept as an alias to LANGUAGES for backwards
compatibility.

See issue #155.

Signed-off-by: Stefan Brüns <stefan.bruens@rwth-aachen.de>

### CODE REVIEW

**Comment by nickoe** [comment]
Looks good to me. Thank you for fixing these issues.

**Comment by ciampix** [comment]
First of all thanks for this.

I was just wondering if it feasible, and if you think that it could make sense, without too much effort, to add the different languages as compilation targets and getting rid of all these variable options (or keeping then... it shouldn't hurt to have more ways to do the same thing...).

I mean enabling something like this:

```
make all (already make all formats for all documents)
make document-name_format-name_all (missing)
make document-name_all_all (missing)
```

**Comment by nickoe** [comment]
What do you mean by "name"? Is that the language code? IMHO I think it is better to stick with the cmake variable to defined the languages compiled.

**Comment by ciampix** [comment]
Examples:
```
eeschema_all_all
eeschema_html_all
```
and I forgot (sorry):
``make document-name_all_language``
example:
`` make eeschema_all_it``

**Comment by nickoe** [comment]
Honestly, I think we should invest more time in trying to make it work with asciidoctor to see if it builds faster than asciidoc. Compilation at the moment is quite slow and I have  the impression that asciidoctor could be faster, although we probably need to drop the epub format.

**Comment by ciampix** [comment]
I could agree. I wish I was able to fix cmake script by myself though... anyway it is not necessarily true that we would have to drop the epub format: ascidoctor-epub3 works fairly well once you have formatted text in a suitable way, that means: master index document without any text content but made only of include directives...

**Comment by StefanBruens** [comment]
regarding `<docname>_all_all` -  I think this is covered by the `<docname>` target. See `make help` for a list of available targets.

**Comment by ciampix** [comment]
Yes definitely. And creating html it is from 10 to 30 time faster (and results are IMHO prettier...)

**Comment by ciampix** [comment]
there are 3 asciidoctor:
* [asciidoctor](https://asciidoctor.org/) (plain) that creates html 
* [asciidoctor-pdf](https://asciidoctor.org/docs/asciidoctor-pdf/) that creates (directly) pdf
* [asciidoctor-epub3](https://asciidoctor.org/docs/asciidoctor-epub3/) that creates epub3

**Pull request merged**
