### PR TITLE
Getting started in KiCad: maintenance (Catalan)

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by ciampix** [comment]
Thanks!

**Comment by kinichiro** [comment]
Hi, @rbuj

Now, building GSiK translation of Catalan (ca) generates WARNING like below,
and these WARNINGs break item 14 and 15 of section 4.1.
<pre>
...
Scanning dependencies of target getting_started_in_kicad_html_ca
asciidoc: WARNING: getting_started_in_kicad.adoc: line 7: missing language conf file: lang-ca.conf
asciidoc: WARNING: getting_started_in_kicad.adoc: line 7: missing section: [footer-text]
asciidoc: WARNING: getting_started_in_kicad.adoc: line 854: list item index: expected 15 got 4
asciidoc: WARNING: getting_started_in_kicad.adoc: line 858: list item index: expected 16 got 15
asciidoc: WARNING: getting_started_in_kicad.adoc: line 868: list item index: expected 17 got 16
asciidoc: WARNING: getting_started_in_kicad.adoc: line 877: list item index: expected 18 got 17
asciidoc: WARNING: getting_started_in_kicad.adoc: line 885: list item index: expected 19 got 18
asciidoc: WARNING: getting_started_in_kicad.adoc: line 890: list item index: expected 20 got 19
asciidoc: WARNING: getting_started_in_kicad.adoc: line 895: list item index: expected 21 got 20
asciidoc: WARNING: getting_started_in_kicad.adoc: line 902: list item index: expected 22 got 21
asciidoc: WARNING: getting_started_in_kicad.adoc: line 906: list item index: expected 23 got 22
asciidoc: WARNING: getting_started_in_kicad.adoc: line 912: list item index: expected 24 got 23
asciidoc: WARNING: getting_started_in_kicad.adoc: line 920: list item index: expected 25 got 24
asciidoc: WARNING: getting_started_in_kicad.adoc: line 928: list item index: expected 26 got 25
asciidoc: WARNING: getting_started_in_kicad.adoc: line 935: list item index: expected 27 got 26
asciidoc: WARNING: getting_started_in_kicad.adoc: line 940: list item index: expected 28 got 27
asciidoc: WARNING: getting_started_in_kicad.adoc: line 942: list item index: expected 29 got 28
Built target getting_started_in_kicad_html_ca
...
</pre>

Here is build/src/getting_started_in_kicad/ca/getting_started_in_kicad.adoc.
We can see line 854 happens to start with '4.', and this causes WARNINGs above.
<pre>
...
    852 14. Si decidiu, per exemple, fer un PCB de 4 capes PCB, aneu a *Regles de
    853     disseny* -> *Configuracio de les capes* i canvieu les ≪Capes de coure≫ a
    854     4. A la taula de les ≪Capes≫ podeu anomenar les capes i decidir com
    855     s'utilitzen. Denoteu que hi ha uns quants preajusts que son molt utils i que
...
</pre>

I think this is a bug of asciidoc, but we need to avoid placing the 'number + .' in the head of line.
For example, removing 'a ' before '4.' solves these WARNINGs.
But I don't know if it is gramatically correct, since I have no knowledge about Catalan.

Next time you maintain ca.po file, could you check this too, please ?

Regards,

**Comment by rbuj** [comment]
Ok no problem, I going to surround the regex [0-9]+'.' with a quotation mark, (i.e. "4." -> "«4»."), Catalan uses French quotation marks (https://en.wikipedia.org/wiki/Quotation_mark).

Regards

**Comment by kinichiro** [comment]
It is good to hear that.

And here is another WARNING about lang-ca.conf.
<pre>
...
asciidoc: WARNING: kicad.adoc: line 6: missing language conf file: lang-ca.conf
asciidoc: WARNING: kicad.adoc: line 6: missing section: [footer-text]
...
</pre>
you can place your own lang-ca.conf in CMakeSupport/ directory of kicad-doc.
cmake detects lang-ca.conf from CMakeSupport/.
I saw you submitted PR for lang-ca.conf to asciidoc project, 
but it seems to take a long time until merged.

Regards,

**Comment by rbuj** [comment]
Done

**Pull request merged**
