### PR TITLE
Clean images in GettingStartedInKiCad

### PR DESCRIPTION
**Pull request by Caerbannog**
This splits icons/ in a dedicated directory. They are freshly generated, and will soon be shared between documents.

All auto generated image names are now gone.

### CODE REVIEW

**Comment by nickoe** [comment]
I thought the idea was to have a global directory for the icons.

**Comment by Caerbannog** [comment]
Yes, I just haven't written a CMake solution for the ePub problem of relative images. This commit will help though, splitting icons from images will be a necessary step.

**Comment by nickoe** [comment]
I guess for a proper epub file we should embed stuff.

**Comment by Caerbannog** [comment]
I think images are always embedded in what they call an OEBPS package, and the root of this package is the .adoc file directory. During the build anything higher is discarded by a2x as being outside of the hierarchy.

**Comment by Caerbannog** [comment]
@nickoe In this rework I moved the icons to a global directory. Summary:
- Remove previous icons from /src/GSIK/images.
- Import recent PNGs to /icons (outside of /src), with a README explaining the generation.
- CMake now duplicates this directory for each translation of each document.
  I could not find a workaround because EPUB genration with `a2x` does not support relative paths with "../",
  and HTML generation with `asciidoc` will interpret paths relative to the `:imagesdir:` variable.
  This `:imagesdir:` has to keep its default value (current doc dir) so that translated images for this document are found.
- This causes two regressions:
     1. Github preview of documents won't find the images
     2. The legacy Makefile won't either
- Update icon paths in GSIK.adoc.

**Comment by Caerbannog** [comment]
This failure is because Jenkins runs the legacy Makefile instead of the CMake scripts. What should I do?

**Comment by nickoe** [comment]
Wait untill I get time to review it properly or ciampix or someone else have some input.

**Comment by Caerbannog** [comment]
To be clear, @ciampix answered in #144 :
> so if you commit this you break the makefile build. If cmake is complete we can just get rid of it altogether but I think it is better to preserve it for now...

Is issue #63 the only thing to resolve before we can call the cmake build system complete?

**Pull request closed without merging**
