### PR TITLE
German translation of GSIK

### LINKED ISSUE #239: GSIK: German translation is WIP
Hello,

I just want to prevent some double work. I've started to work on the German translation for getting_started_in_kicad. But I will need a few more days. Thanks.

### PR DESCRIPTION
**Pull request by tijuca**
Please consider pulling my work for a translation of GSIK into German.
I added some additional screen shots with German locales to get relationship between the translated part and the respective screen shot.
Currently I have some trouble on chapter 4.1, point 16. I don't know why the translated string and the related screen shot isn't used.

This pull request would also close #239 if accepted.

Regards
Carsten

### CODE REVIEW

**Comment by ciampix** [comment]
Thanks!

**Comment by kinichiro** [comment]
Hi, @tijuca

> Currently I have some trouble on chapter 4.1, point 16. I don't know why the translated string and the related screen shot isn't used.

It seems that your de.po file has a inconsistency with original .adoc file.
You need to update po file by commands below. (Also see closed issue https://github.com/KiCad/kicad-doc/issues/209)

Place your latest de.po under src/getting_started_in_kicad/po/ , 

    cd src/getting_started_in_kicad/
    touch *.adoc
    make -f ../../utils/old-build-scripts/Makefile po/de.po 

After updating, edit de.po with poedit again.

BTW, I would like to recommend that renaming images/de/custom_tracks_width*s*.png 
to images/de/custom_tracks_width.png, since original filename is it.

Regards.

**Comment by ciampix** [comment]
Thanks @kinichiro for the explanation!

**Comment by tijuca** [comment]
Awesome guys! That worked, thanks!
I'll prepare a new pull request.

**Pull request merged**
