### PR TITLE
add chapter 4 to spanish pcbnew manual

### PR DESCRIPTION
**Pull request by AntonioMR**

### CODE REVIEW

**Comment by ciampix** [comment]
Thank!

**Comment by kinichiro** [comment]
Hi, @AntonioMR 
It seems that some numbers of '\n' between 'msgid' and 'msgstr' are different in pcbnew/po/es.po.
Then, if you try to update po now, you will get errors like below.
<pre>
$ cd kicad-doc/src/pcbnew/
$ touch *.adoc
$ make -f ../../utils/old-build-scripts/Makefile po/es.po
Parse input files...
done.
Updating po/es.po:
................................................................................................................................... done.
po/es.po:1767: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:1781: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:2410: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:2440: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:2457: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:2608: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:2720: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:2730: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:2867: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:2875: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:4046: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:4410: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:4690: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:4907: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:4919: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:4951: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:4963: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:7350: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:7363: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:7384: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:7417: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:7463: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:7529: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:7605: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:7614: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:7812: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:9163: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:9190: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:9316: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:10567: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:10622: 'msgid' and 'msgstr' entries do not both end with '\n'
po/es.po:10781: 'msgid' and 'msgstr' entries do not both end with '\n'
msgfmt: found 32 fatal errors
po/es.po: 1173 translated messages, 3 fuzzy translations, 133 untranslated messages.
$
</pre>
I would like to suggest to fix this issue, since this might break build of pcbnew_epub_es.

Best Regards,

**Comment by AntonioMR** [comment]
Ok. I see.
I'm going to see what can I do.
Thanks for your advice.

**Comment by ciampix** [comment]
Fixed.

**Comment by AntonioMR** [comment]
You were faster!
@ciampix thank you very much for your invaluable help

**Pull request merged**
