### PR TITLE
Workflow and annotation sections review

### PR DESCRIPTION
**Pull request by evanshultz**
I'm not keen on the sentence "Some do not consider this particular feature especially useful." in regards to Backward Annotation, but I'm leaving it for now. Anyone else what to remove it or change it? Also retitled the section under Using KiCad since it was just repeating the following two sections and the term "shortcut" should be more obvious to a new KiCad user. It's weird: I feel that I already submitted a patch for this...

### CODE REVIEW

**Comment by evanshultz** [comment]
@ciampix when you review and hopefully merge this, please note that only the Workflow and Annotation sections should be changing. Other patches to GSIK have been merged and I'm not sure how smoothly GitHub will handle this patch being merged.

**Comment by evanshultz** [comment]
Would it be possible to get a review and/or merge for this PR? I'd like to get this resolved before moving forward in the document. @ciampix?

**Comment by ciampix** [comment]
I think it is all Ok. Waiting the Travis CI to finish to push & close this, many thanks!

**Comment by ciampix** [comment]
Apart from this, I would like to contact you Evan. Please send me an email...thanks...

**Comment by evanshultz** [comment]
@ciampix I don't have your email, but you can contact me at neaterbookmarks (at) gmail (dot) com.

**Comment by evanshultz** [comment]
@ciampix This PR was closed without merging the patch. Was that an accident or is there an issue?

**Comment by ciampix** [comment]
Sorry... my fault.. thanks

**Pull request merged**
