### PR TITLE
Try to fix chinese pdf problem

### PR DESCRIPTION
**Pull request by CNLHC**

### CODE REVIEW

**Comment by CNLHC** [comment]
Hello,
I just add extra configuration for Chinese translation building process, and unfortunately my branch didn't pass the check.  The error is  quite weird :

    `a2x: ERROR: "dblatex" -t pdf -p "/etc/asciidoc/dblatex/asciidoc-dblatex.xsl" -s 
    "/etc/asciidoc/dblatex/asciidoc-dblatex.sty" -P latex.output.revhistory=0 -P doc.publisher.show=0 -s 
    /home/travis/build/KiCad/kicad-doc/CMakeSupport/pdf-cover-dblatex.sty -b xetex -p 
    /home/travis/build/KiCad/kicad-doc/src/cvpcb/../../xsl/dblatex-pdf-ja.xsl -b xetex -p 
    /home/travis/build/KiCad/kicad-doc/src/cvpcb/../../xsl/dblatex-pdf-ru.xsl -b xetex -p 
    /home/travis/build/KiCad/kicad-doc/src/cvpcb/../../xsl/dblatex-pdf-zh.xsl -o 
    /home/travis/build/KiCad/kicad-doc/build/src/cvpcb/en/cvpcb.pdf  "/home/travis/build/KiCad/kicad- 
    doc/build/src/cvpcb/en/cvpcb.xml" returned non-zero exit status 1
    make[2]: *** [src/cvpcb/en/cvpcb.pdf] Error 1
    make[1]: *** [src/cvpcb/CMakeFiles/cvpcb_pdf_en.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 55%] Built target plugins_pdf_ru
    [ 55%] Built target cvpcb_pdf_ja
    [ 55%] Built target cvpcb_pdf_ru
    make: *** [all] Error 2
    `  

My branch  let the Russian version building process failed.

I don't know much about `a2x`, but are its parameters correct? 

As error info show above, if you don't specify `SINGLE_LANGUAGE` setting  while invoking the `CMake`, the `a2x` will pass all the extra configuration settings to  the `dblatex`, including `dblatex-pdf-ja.xsl `, `dblatex-pdf-ru.xsl`, `dblatex-pdf-zh.xsl `.  

Could someone please tell me Is that why the error occur?

Thanks.

**Comment by ciampix** [comment]
I'll investigate, sorry for the delay...

**Comment by ciampix** [comment]
If this is it: http://ci.kicad-pcb.org/job/any-kicad-doc-pull-request/
I see this:
a2x: ERROR: missing resource: /home/kicad/workspace/any-kicad-doc-pull-request/build-cmake/src/cvpcb/zh/images/zh_CN/3d_window.png

**Comment by ciampix** [comment]
unfortunately it is missing a "make test" command to see if it at least compile, for example checking for missing images links that block the epub generation...

**Comment by CNLHC** [comment]
@ciampix  Thanks for your advice.

But i think the link you post  is not the error of this PR.  that error was caused by #570 , and it's you who solved that  problem.

I have configured  Travis CI for my forked repo,  I will do more investigation without messing the main repo.

BTW,  about the problem of `a2x` parameters, do you know if the `cmake` was  designed to generate parameters  like this or it is a BUG?

**Comment by ciampix** [comment]
@CNLHC Check for all fonts (especially asian fonts) or asciidoc highlighter missing...

**Comment by ciampix** [comment]
and asian languages latex support obviously...

**Comment by ciampix** [comment]
Hi @CNLHC I having some problems compiling the Italian language too. It is strange since it used to work (and still works) with my old compilation scripts (still present in sources). Really seems to be a cmake script bug. I'm committing it. Hope this solves the problems with other languages too...

**Comment by ciampix** [comment]
Found the source of the problem: new eeschema simulation section has malformed tables due to incoherent docs on asciidoc format (but I am still investigating and asking the asciidoc gurus). Po4a is strinctly adherent on (old?) standard of 4 (or more) chars delimiter for tables that was made of just 3 ... fixed sources now compile the Italian ... try with the Chinese version if it was that...

**Comment by CNLHC** [comment]
@ciampix Thank you for reply.  I have't translated `eeschema` document to Chinese, so Chinese version problems were not caused by this reason. 

Since you mentioned the newer tools, i have a little bit more to say..

With the latest version tools. I couldn't perform a full compiling in my laptop, there always have some strange errors. 

Although  the code pass the Travis CI check(e.g. #587 ),  I couldn't compile it locally. So, I think there may be some subtle problems caused by some newer version tools.

This is tools version  in my laptop(with Ubuntu-18.04, and all these tool were installed by ` apt ` command from official sources)  

    -- Found DBLATEX: /usr/bin/dblatex (found version "0.3.10") 
    -- Found PO4A: /usr/bin/po4a (found version "0.52") 
    -- Found ASCIIDOC: /usr/bin/asciidoc (found version "8.6.10") 
    -- Found A2X: /usr/bin/a2x (found version "8.6.10") 
    -- Found Git: /usr/bin/git (found version "2.17.0") 

And this is tools version in Travis CI.

    -- Found DBLATEX: /usr/bin/dblatex (found version "0.3.4") 
    -- Found PO4A: /usr/bin/po4a (found version "0.45") 
    -- Found ASCIIDOC: /usr/bin/asciidoc (found version "8.6.9") 
    -- Found A2X: /usr/bin/a2x (found version "8.6.9") 
    -- Found Git: /usr/bin/git (found version "2.15.1") 

Maybe we need more investigations.

**Comment by ciampix** [comment]
I think this is a dblatex (Debian stable?) bug since I have an Ubuntu 18.04 as you and it works perfectly.
Why not recreate the machine as an Ubuntu server?

**Comment by ciampix** [comment]
I have prepared a Debian stable compiling machine... it is compiling now ... I had to add this package: apt-get install texlive-xetex
did you add it?

**Comment by tijuca** [comment]
All these packages are explicitly mentioned on the README.adoc file and should be installed by the listed command. I found some extra packages that are installed as a Recommends that may be missed on some systems if the user don't want to have installed such recommended packages. The list needs to be extended by `asciidoc-dblatex docbook-xsl libunicode-linebreak-perl` at least on Debian Stretch (probably also Jessie). Debian Testing will be the same I guess but I haven't tested this finally yet.

But yes, the cmake checking could be much better here to detect missing packages.

**Comment by ciampix** [comment]
With the current Stable Debian all the mentioned packages in the README.adoc are sufficient for getting the whole docs compiled without problems... anyway seems that the error was the use of an obsolete version of Debian...

**Pull request closed without merging**
