### PR TITLE
CvPcb fr.po, chapter 5

### PR DESCRIPTION
**Pull request by MarcusFecit**

### CODE REVIEW

**Comment by ciampix** [comment]
retest this please

**Comment by MarcusFecit** [comment]
What do you mean by "retest" ?

**Comment by ciampix** [comment]
It used to be in place an automated scripting build active and that string (google for "retest this please github") fire it on. I am just verifying if it is still active. Just forget it, is is not a comment directed to you...

**Comment by ciampix** [comment]
Thanks, seems all ok.

**Pull request merged**
