### PR TITLE
Fix Chinese translation and typographical errors

### PR DESCRIPTION
**Pull request by taotieren**

### CODE REVIEW

**Comment by taotieren** [comment]
@CNLiuGuang Pcbnew 还是编译有问题，准备用笨办法来处理了，这次 pull 是修复了一些排版问题和manjaro环境的搭建

**Comment by taotieren** [comment]
@ciampix Hi,This time the pull can be merged, I am going to fix the pcbnew compilation error.

**Comment by ciampix** [comment]
Thanks!

**Comment by taotieren** [comment]
@ciampix :wink:

**Pull request merged**
