### PR TITLE
Add chinese translation for gui_translation_howto and idf_exporter

### PR DESCRIPTION
**Pull request by taotieren**
Add chinese translation for gui_translation_howto and idf_exporter,Fix  chinese translation errors for getting_started_in_kicad.

### CODE REVIEW

**Comment by taotieren** [comment]
`[ 74%] Generating ru/idf_exporter.pdf
a2x: ERROR: "dblatex" -t pdf -p "/etc/asciidoc/dblatex/asciidoc-dblatex.xsl" -s "/etc/asciidoc/dblatex/asciidoc-dblatex.sty" -P latex.output.revhistory=0 -P doc.publisher.show=0 -s /home/travis/build/KiCad/kicad-doc/CMakeSupport/pdf-cover-dblatex.sty -b xetex -p /home/travis/build/KiCad/kicad-doc/src/idf_exporter/../../xsl/dblatex-pdf-zh.xsl -o /home/travis/build/KiCad/kicad-doc/build/src/idf_exporter/zh/idf_exporter.pdf  "/home/travis/build/KiCad/kicad-doc/build/src/idf_exporter/zh/idf_exporter.xml" returned non-zero exit status 1
make[2]: *** [src/idf_exporter/zh/idf_exporter.pdf] Error 1
make[1]: *** [src/idf_exporter/CMakeFiles/idf_exporter_pdf_zh.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 74%] Built target idf_exporter_pdf_en
[ 74%] Built target idf_exporter_pdf_pl
[ 74%] Built target idf_exporter_pdf_ru
make: *** [all] Error 2
The command "mkdir build && cd build && cmake .. && make -j4" exited with 2.`

**Comment by ciampix** [comment]
@taotieren please also have a look to #639 ...

**Comment by ciampix** [comment]
Thanks!

**Comment by taotieren** [comment]
thanks

**Pull request merged**
