### PR TITLE
fix build Russian pdf and epub

### PR DESCRIPTION
**Pull request by kinichiro**
- add xsl/dblatex-pdf-ru.xsl to use package xecyr

### CODE REVIEW

**Comment by kinichiro** [comment]
Hi,
for PR #333 , it seems that additional .xsl file
for Russian doc is required as same as Japanese doc.

After installing package `texlive-lang-cyrillic`,
I could succeed to build GSiK Russian pdf and epub.

Thanks.

**Comment by ciampix** [comment]
Thanks! I was figuring that out but you did it faster!

**Comment by baranovskiykonstantin** [comment]
I'm checked html only. Sorry((

**Comment by kinichiro** [comment]
@baranovskiykonstantin no problem.
I am also glad to see new language doc :-)

@ciampix thanks for merging.
But, build seems still failing.
I could build on my local ubuntu 15.10, 
so I think `texlive-lang-cyrillic` or something
is missing, maybe.

**Comment by ciampix** [comment]
@baranovskiykonstantin yes no problem and thanks! You did well. You just triggered an existing problem but it's not your fault.

@kinichiro I am able to compile it in my Ubuntu 14.04 too. Wrote to @nickoe to make him see to it. IMHO it's a builder machine problem...

**Comment by nickoe** [comment]
Hi, @kinichiro and @ciampix I have been trying to figure out why it does not build and I can't seem to fix it right now. I have installed all the texlive stuff that relates to cyrillic stuff, but I see issues that might relate to the freeserif fonts like:

```
kpathsea: Running mktexmf FreeSerif

! I can't find file `FreeSerif'.
<*> ...jfour; mag:=1; nonstopmode; input FreeSerif

Please type another input file name
! Emergency stop.
<*> ...jfour; mag:=1; nonstopmode; input FreeSerif

Transcript written on mfput.log.
grep: FreeSerif.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input FreeSerif' failed to make FreeSerif.tfm.
```

**Comment by kinichiro** [comment]
Hi, @nickoe

Is your Jenkins build server Fedora ?

@ciampix and I use Ubuntu and it seems to have FreeSerif font in default.
<pre>
$ fc-list | grep  FreeSerif.ttf
/usr/share/fonts/truetype/freefont/FreeSerif.ttf: FreeSerif:style=Regular,нормален,normal,oby?ejne,Mittel,μεσα?α,Normaali,Normal,Normale,Gemiddeld,odmiana zwyk?a,Обычный,Normalne,????,menengah,прям?й,Navadno,vid?js,normalusis,????,v?a,Arrunta,???????
</pre>

I thought fonts FreeSerif/FreeSans/FreeMono are used well in any linux distributions,
then I put them into xsl/dblatex-pdf-ru.xsl.
It was my mistake, sorry.

Should we choose other cyrillic font that is available on several build environments ?
@baranovskiykonstantin do you have any idea for good cyrillic font ?

**Comment by baranovskiykonstantin** [comment]
Hi. I'm using Archlinux. I had the same issue with FreeFont and had resolved this issue by installation the ttf-freefont package. But, anyway, FreeFont is good for me. Maybe we need to add an additional dependency like it done for japanese language?

**Comment by kinichiro** [comment]
on Fedora, FreeFont is obtained by this command.
`sudo dnf install gnu-free-serif-fonts gnu-free-mono-fonts gnu-free-sans-fonts`

**Comment by nickoe** [comment]
@kinichiro ahh, thanks, that seemed to fix it.

**Comment by kinichiro** [comment]
@nickoe it is good to see build succeeded.
We should add these 3 fonts packages into Fedora section of README.adoc.

**Comment by ciampix** [comment]
Fixed, thanks to all!

**Pull request merged**
