### PR TITLE
new try: Start translation of Pcbnew to German, add Style definitions for writing style policy

### PR DESCRIPTION
**Pull request by transistorgrab**
Hi,

this is my second try to get my changes back to KiCad. Hope it works this time. :)

### CODE REVIEW

**Comment by tijuca** [comment]
You already mixed again two various parts, split out the translation things from the expanding of the style policy things and create a separate pull request for this or rebase the commits at least in a logical order.

You use for three commits the same topic (Update doc_wrinting_style_policy.adoc), I would assume that all three commits are the same thing but spited out into three commits. Why? Rename them to a proper topic. And explain why you doing these kind of things.

5e881b1 better topic would be 'add addendum.de file for Pcbnew' or I prefer some prefixing 'Pcbnew: add addendum.de control file' or similar
a9e2e3f What style definitions? Where?
1877ab9 Why not melding into 29fbdec directly? For me there is no need to create one more commit.

**Comment by transistorgrab** [comment]
Hi tijuca,

well... as I wrote earlier I'm not a software developer and not much familiar to such things.
Here my view on this topic:
Since the addendum files are the first step in starting a translation I think it's not necessary to put it in a single commit/branch on it's own. I agree I could have put this in the commit message.
I agree with the suggestion to split style and translation into different branches and will do it from now on (already created a branch locally for the further translation).
If I add further content to the writing style I will create a branch for it also.
The style definitions are a separate file with exactly that in the file name so I thought it would be obvious – which it is not – obviously. :)
Again: I understand what you are telling me.
For this commit I request to accept it as is for this time only, since I think it will not break anything already in place. I'm still confused how to clean this up without doing double work. I was happy to get the conflicts resolved with the help of some tutorial I found elsewhere.
I will try to keep my commits cleaner further on, but since there is no process definition around (at least I did not find one), it is learning by doing – and for people not at home in software development there is a learning curve…
Is there any guideline that helps me to do better from now on?

**Comment by kinichiro** [comment]
Hi,

Basically, 1 PR(pull request) should contain 1 modification.

I think your PR contains 2 modifications,
one is Pcbnew German translation work,
the other is updating doc_wrinting_style_policy.adoc.
These are the different work, one is translation work and 
the other is updating base document.

So, why not submit 2 PRs, like below.
<pre>
(1) German translation for Pcbnew
 1. Start new German translation for Pcbnew
 2. add German translations for Pcbnew documentation
 7. Update translation for Pcbnew to German …

(2) Update doc_wrinting_style_policy.adoc
 3. Update doc_wrinting_style_policy.adoc
 4. Update doc_wrinting_style_policy.adoc
 5. Update doc_wrinting_style_policy.adoc
 6. Add Style definitions.
</pre>

Regards,

**Comment by tijuca** [comment]
Hello transistorgrab,

I can understand your feelings, and that's why I wrote that Git can be annoying if you do it not right. And to get some learning without big frustration I have wrote a email to you in private with some offering to help. Sadly you didn't reply.

kinichiro is exactly saying what to do next, I was talking about the same. To solve your problems and getting everything in a good shape for acceptance of your patches you need to rework your patch queue again. But there is no learning without doing, btw I'm also no software engineer. And it's not that difficult. If you still want to get some help please get in contact with me, I will try to guide you.

The "GitHub pull request workflow" isn't very helpful in such case like this and in the end there is no big difference if the commits there merged in one go or more, but there is no mailing list or document for better clearance (as you noted).

**Comment by transistorgrab** [comment]
I think the main problem on my side is:
I did not know that github merges further commits into the same (open) pull request.
So I first opened a pull request for the translation, then did some work on the writing style document, pushed my local changes to github in the hope that after the first pull request is granted I would ask to pull the next changes. :-/
Obviously that did not work as expected. (also my latest translations were merged into that new pull request too…)
Will do further reading on this topic and try to sort it out. may take some time though, vacations are over…

**Comment by kinichiro** [comment]
Hi @transistorgrab 
I feel github and PR is difficult to understand at first.

I would like to suggest using different branch for each PR.
You appear to do your all modifications on `master` branch only.
Keeping your `master` branch as same as here (Kicad:master) is simple way.

Create `pcbnew_de` branch from `master` and do your translation work there,
then submit PR with your `pcbnew_de` branch.

Next, go back to once `master`,
and create `update_writing_style` branch from `master` again,
do your work there, then submit PR with your `update_writing_style` branch.

1 modification / 1 branch (may contain several commits) / 1 pull-request is simple way.

Once your PR is merged, you should delete your working branch.
(You can see the delete branch button after PR is merged.)
And refresh your `master` with here (Kicad:master).

Best Regards,

**Comment by transistorgrab** [comment]
Thanks for all your comments and encuragement, working on solving this,

**Pull request closed without merging**
