### PR TITLE
Remove libre office meta tags from template creation

### LINKED ISSUE #704: How to make a template section has strange libre office specific lines in html example.
A user just reported on the forum that they are confused about some details of the how to make a template section. Specifically the meta tags found in the html example that i assume are not necessary but are there because the example file was created using libre office.
Any objections on removing these lines?

### PR DESCRIPTION
**Pull request by poeschlr**
Fixes #704 

I also noticed that the html body tag sets the language to french. (But the text is clearly english.)
Is this also ignored by kicad (meaning we can remove this as well) or should we change it to english.

### CODE REVIEW

**Comment by ciampix** [comment]
Thanks!

**Comment by poeschlr** [comment]
What do you think about the language specifier? Should we delete it or change to english?

**Comment by ciampix** [comment]
If you leave it, change it into English. If you think it is worth, open a BR to enable translation of the templates (i.e. handling the language tag...)

**Comment by poeschlr** [comment]
Does kicad even use that attribute? If not then i doubt it would be worth having this in the example even if we want the example html to be translated. (I think the example does not necessarily need translation but that is for others to decide. I have not even looked deep enough into how the documentation stuff works to know how to use translation.)

**Comment by ciampix** [comment]
IHMO we can leave it and add a note that, actually, language tags are not handled (yet?)
Maybe in the future...

**Comment by nickoe** [comment]
If not used, lets just remove it? I mean it is a template afterall.

**Comment by ciampix** [comment]
Yes as I said, _if_ you leave it, then make it correct... but remove any unused tag is generally a good policy

**Pull request merged**
