### PR TITLE
Pcb_Calculator documentation

### PR DESCRIPTION
**Pull request by heitorPB**
Working in progress (do not merge yet).

I'd like some feedback in the documentation of PCB_Calculator that I started.

The LaTeX equation is rendering nicely, but asciidoc adds some huge space around it:
eq

TODO list:
- [ ] Fix equations
- [ ] Introduction text
- [ ] Regulators
- [ ] Track Width
- [ ] Electrical Spacing
- [ ] TransLine
- [ ] RF Attenuators
- [x] Color Code
- [ ] Board Classes

### CODE REVIEW

**Comment by ciampix** [comment]
What do you mean with: "The minimal Values which orientatd at the IPC-2221 too."?

**Comment by evanshultz** [comment]
@ciampix 
IPC-2221 specifies many aspects of PCB manufacture and it's one common standard to use for track width and track spacing. While I didn't review anything, it would be understood from these comments that a user can enter information and the resulting track width and spacing is derived from information in this IPC document.

I suggest this needs run though a spell-checker and a good polish of the English before merging. Both are visible in the quote above.

**Comment by heitorPB** [comment]
I'm closing this PR as @alfrede continued the work and his PR #680 was merged.

**Comment by nickoe** [comment]
Ok, thanks.

**Pull request closed without merging**
