### PR TITLE
yet more synonyms

### PR DESCRIPTION
**Pull request by carycode**
mention the actual names shown in the current KiCad Gerber dialog.

### CODE REVIEW

**Comment by ciampix** [comment]
retest this please

**Comment by nickoe** [comment]
I need to update jenkins after the recent changes.

**Comment by nickoe** [comment]
retest this please

**Comment by nickoe** [comment]
@carycode Maybe we should just remove the old layer names?

**Comment by carycode** [comment]
@nickoe: I agree that we should *eventually* remove the old layer names. However, rather than try to transition all-at-once, I prefer to start by making a table like this one that mentions both the (deprecated) old names and the new names and how they match up. Later, after we are pretty sure that all the other documentation has been updated to use the new names, after that removing the old names.

That way when I see the old name in some other documentation,
this table tells me immediately what the new name is.

What else do I need to do to get the actual names used by the current version of the software into the current version of the documentation?

**Comment by kinichiro** [comment]
@carycode I've done for this issue like this,
http://docs.kicad-pcb.org/en/getting_started_in_kicad.html#generate-gerber-files
Could you check about this, please ?
Thanks.

**Comment by nickoe** [comment]
@kinichiro I think that we should mentions that those gerber file name extensions are when one have selected the protel filename option.

**Comment by kinichiro** [comment]
@nickoe How about adding this note after the table ?
<pre>
NOTE:
The Gerber File Extensions in the table above are used when you Plot
with checking *Use Protel filename extensions* in the Gerber Options.
If this option is disabled, all the gerber files are generated with
the extension _.GBR_.
</pre>

**Comment by nickoe** [comment]
@kinichiro I guess that is good.

**Comment by kinichiro** [comment]
@nickoe Thanks, I'll post a PR soon.

**Comment by ciampix** [comment]
May I close this one? Is it resolved with the #186 merge?

**Comment by nickoe** [comment]
Yeah, looks resolved to me.

**Pull request closed without merging**
