### PR TITLE
Spanish Pcbnew manual translation finished

### PR DESCRIPTION
**Pull request by AntonioMR**

### CODE REVIEW

**Comment by ciampix** [comment]
Thanks!

**Comment by kinichiro** [comment]
Hi, @AntonioMR 

I noticed that src/pcbnew/po/es.po has 1 issue, here.
<pre>
  10594 #. type: Target for macro image
  10595 #: pcbnew_zones.adoc:217
  10596 #, no-wrap
  10597 msgid "images/Pcbnew_zone_corner_move_during.png"
  10598 msgstr "Aqui esta una esquina (de un corte) que se ha movido:"
</pre>

In this case, msgstr should be .png file name, since msgid indicates .png file name.
This issue causes doc build error, since tool can not find the .png file.

Best Regards,

**Comment by AntonioMR** [comment]
Hi @kinichiro 
Sorry and thanks for your warning
I've fixed it with PR #297 
Regards

**Comment by kinichiro** [comment]
Hi @AntonioMR 
Thanks for your fixing src/pcbnew/po/es.po.
It is good and I confirmed doc build succeeds.

**Pull request merged**
