### PR TITLE
Edit GSIK and Pcbnew PO catalog files to remove fuzzies

### PR DESCRIPTION
**Pull request by keruseykaryu**
PO catalogs were not updated to include latest changes in english sources. 
I have no possiblilty to do this from Win. Sorry.

### CODE REVIEW

**Comment by nickoe** [comment]
@keruseykaryu I guess you want this in, and do you want me to update the polish po files for you?

**Comment by nickoe** [comment]
@keruseykaryu I pushed an update of the po file for pl, apparently it only updated it for eeschema.

**Comment by keruseykaryu** [comment]
Tables to full re-translate... Oh, no. Not again. :(

**Comment by nickoe** [comment]
What?

**Comment by keruseykaryu** [comment]
12 tables has been updated and need to be fully translated again (Old translations were removed instead of mark them as "fuzzy"). Translation this kind of text with Poedit is quite embarrassing.

**Comment by ciampix** [comment]
Mmmm ... perhaps there is something wrong in the cmake scripts or po4a asciidoc has something wrong dealing with tables ... in these days I'll try see if that is our fault or a po4a problem... thanks for the heads up and sorry for any inconvenience this could have caused... there is no other way to solve problems... unfortunately!

**Comment by keruseykaryu** [comment]
Done. https://github.com/KiCad/kicad-doc/pull/692

**Pull request merged**
