### PR TITLE
Pcb_Calculator documentation #631 fixed

### PR DESCRIPTION
**Pull request by alfrede**
Hi all,

i just finished the Documentation for the PCB Calculator. Please have a look and say if it's okay.

### CODE REVIEW

**Comment by alfrede** [comment]
Can somebody please help me, i don't understand the failure.

**Comment by tijuca** [comment]
Well, your changes have broken the build. The exact reason is visible in the Travis log. Sometimes the build is breaking on languages like Japanese or Chinese, but you have already a problem with the English language. You need to dig into this error messages and do the build step by step manually.

I'm quite sure nobody can follow you (or is willing) to follow your modifications as don't explain why you did change something within the various commits. Maybe it's time to rethink the sense of commit messages!

https://github.com/erlang/otp/wiki/writing-good-commit-messages

**Comment by alfrede** [comment]
Tested with the verbose command and seen that the logo file was missing in the images folder.

**Comment by ciampix** [comment]
As soon as it build I have merged it... :-) Please as said by @tijuca use more meaningful comments for the commits next time...

**Comment by alfrede** [comment]
Yes okay, next time i promise i will write good comments, but after all one question, why was the pdf was made on my computer okay and on the build setup not? And where can i see that the logo file is need?

**Comment by ciampix** [comment]
Good question ... :-) I had to make some personal make files for enabling some debug on pdf compilation (sometimes pdflatex is very tricky to debug...), all because I am very ignorant on cmake

**Comment by nickoe** [comment]
@tijuca it is not that big of a deal if people to make multiple commits on a pr to pass travis, it can be squashed even in the github webui.

@ciampix I would have prefered that the commit was modified to be more meaningful, that is to remove the test comments from the final commit.

@alfrede thank you for your contribution. :)

**Comment by ciampix** [comment]
@nickoe yeah my bad you're right of course, sorry!

**Comment by tijuca** [comment]
@nickoe 
I know that mostly everything can be fixed if you know how git is working and how to use it. But for my understanding it's really a bad attitude to bring such PRs into public as obviously it's not ready. And there is nothing more easy that people can test their PRs again and agin in their repo before they start a official PR! But yeah, make it idiot proof ...

Maybe my requirements sounds to high, if this is the case I will simply step down on contributions and only will do some packaging.

**Pull request merged**
