### PR TITLE
Added translation for spanish

### PR DESCRIPTION
**Pull request by AntonioMR**
Added spanish translation for Eeschema manual

### CODE REVIEW

**Comment by ciampix** [comment]
Very good, thanks!

**Comment by nickoe** [comment]
http://ci.kicad-pcb.org/job/any-kicad-doc-head/125/console

**Comment by ciampix** [comment]
Yes thanks I am trying to figuring it out...

**Comment by AntonioMR** [comment]
is anything I've done wrong?

**Comment by ciampix** [comment]
yes but I fond an error even in the main source file so... don't worry...

**Comment by ciampix** [comment]
every translator contribute to find a bunch of errors in the main files and/or in that crappy dblatex (that we have to circumvent somehow...)

**Pull request merged**
