### PR TITLE
Improve pl_editor Chinese image link

### PR DESCRIPTION
**Pull request by taotieren**

### CODE REVIEW

**Comment by nickoe** [comment]
It lools like you reuploaded the old branch. I guess that the new change is only the last commit.

I suggest you to use a local branch for your pull requests. You should also be able to do a rebase when you pull to avoid the merge commits.  `git pull -r` or `git rebase` kf you already made the merge commit.

**Comment by tijuca** [comment]
Commit messages that are equal are a stupid idea. The command `git log` will show them also with the same topic! If the commits are basically about the same part than you should rebase them together, otherwise give a hint what has changed like `'chapter 2: $something foo bar'`.

**Comment by ciampix** [comment]
Will you please see to the conflict files? So I can go on and approve the pull request...

**Comment by taotieren** [comment]
@ciampix Sorry.I found that pcbnew didn't compile, and then found the compilation problem inside, found some other problems, and also fixed the problem of other documents, forgot to turn off the pull

**Comment by taotieren** [comment]
It is best not to approve, has not fixed the problem of pcbnew Chinese documents,

**Comment by taotieren** [comment]
At present, only pcbnew Chinese documents have compilation problems. The rest have fixed many errors, and have not been compiled and tested. If they are merged, please temporarily remove pcbnew Chinese documents（pcbnew/po/zh.po）.

**Comment by taotieren** [comment]
@tijuca I will merge these commints the next time I submit, and I am still looking for pcbnew Chinese documents.

**Comment by tijuca** [comment]
@taotieren 
Sure and thanks!

**Pull request closed without merging**
