### PR TITLE
Finish changes for issue #226

### PR DESCRIPTION
**Pull request by evanshultz**
Add new hotkey syntax, remove a now-unneccesary note about viewing the hotkey list, and change "shortcut keys" to "hotkeys". I would appreciate a review by @ciampix and @kinchiro and @nicknoe, if you're interested. I also fixed one admonition. Note that I haven't reviewed for clarity and do see opportunities to improve this document; right now all I'm doing to is addressing the above issue.

### CODE REVIEW

**Comment by kinichiro** [comment]
Hi, @evanshultz 
Thanks for your great works and I think this fix is good.

This is my personal feelings, though,
For Insert and Delete hotkey, I would like to add brackets too,
like [Insert] and [Delete] since the convention note describes below;
`In this document, hotkeys are expressed with brackets like this: [a]`
How do you think about this ?
If just Insert and Delete is better than with brackets, I'm OK.

Best Regards,

**Comment by evanshultz** [comment]
Let me first understand. I believe you feel that adding the brackets makes it more clear that a particular key needs to be pressed, so the user has the think less about the content and can more easily follow the Getting Started guide. I like that idea.

It's a good question. I searched Google for a bit with queries like ""getting started" "delete key"", ""getting started" "press delete"" and ""user guide" "delete key"", etc. I found the following nomenclatures:
-DELETE key
-Delete key
-"Delete" key
-'Delete' key
-<Delete> key

It seems special characters are stripped out, so I think my searching of this type was bogus as the brackets were being excluded and gave me false negatives that brackets are used.

I then tried to check out style guides and keyboard shortcuts, to see what the computer/OS vendors and document creation folks say. Other than all caps being out of style, I didn't find anything else helpful.

All told, I see little consensus and thus haven't developed a sense of "right" and "wrong". It seems any of the numerous ways can be equally as instructive to the reader. So with that in mind, I vote to wait a couple days for anyone else to chime in and, if not, add the brackets and move on from this issue. OK?

**Comment by nickoe** [comment]
To me it is more important that it is easily readable, it it gets easier to read it with brackets around keys, then ok.

But I have to say that; "Edit by hovering over the pad and press the e key.", is fairly readable by itself. This wa just a made up example.

**Comment by ciampix** [comment]
Well, it seems that this way to present key combination nicely fits an "experimental" feature of asciidoctor:

http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#ui-macros

Given that I see a transition from asciidoc (actual python executable asciidoc compiler) to asciidoctor (ruby modern asciidoc compiler - used by github for example) for our docs compilation scripts in the future, for a number of reasons, I agree to this (key combinations surrounded by brackets).

**Comment by ciampix** [comment]
There is even a macro example that could be just right for us... 

https://gist.github.com/mojavelinux/4736691

let me do some experiments ... then I may have the need of a cmake expert :-)

**Comment by kinichiro** [comment]
Yes, as you say in your comment, I just wanted to indicate the key is particular one.
And, Yes, I would like to wait some experiments of @ciampix .

**Comment by evanshultz** [comment]
In the interim, @ciampix would you be willing to merge my patch? I'd like to continue working on this doc but am afraid of breaking it if I continue on to later sections. It seems to me that merging this patch is safe, and a new patch in the future with the cool button style will work nicely.

**Comment by ciampix** [comment]
Yes of course, as soon as Travis ends the check. Thanks!

**Comment by ciampix** [comment]
Thanks!

**Pull request merged**
