### PR TITLE
Improve kicad Chinese translation

### PR DESCRIPTION
**Pull request by taotieren**

### CODE REVIEW

**Comment by nickoe** [comment]
It looks like you forgot to add images/zh/launch_pane.png

**Comment by ciampix** [comment]
a2x: ERROR: missing resource: /home/travis/build/KiCad/kicad-doc/build/src/kicad/zh/images/zh/project_tree.png

**Comment by taotieren** [comment]
Received, fixed

**Comment by taotieren** [comment]
I want to use 
images/launch_pane.png.
images/project_tree.png.Habitually add /zh/ to the image link when editing zh.po

**Comment by taotieren** [comment]
Use existing images to save warehouse space

**Comment by taotieren** [comment]
Hi,Does kicad-doc have a telegram group?

**Comment by nickoe** [comment]
Not that I know of. There are quite some people on IRC at #kicad on freenode

**Comment by nickoe** [comment]
Thank you.

**Comment by taotieren** [comment]
@nickoe thanks，I know

**Comment by ciampix** [comment]
there is a general kicad telegram group though...
https://t.me/kicadcommunity

**Comment by taotieren** [comment]
@ciampix Thanks.

**Pull request merged**
