### PR TITLE
Pcbnew german

### PR DESCRIPTION
**Pull request by transistorgrab**
Finished today the German translation for Pcbnew. Since the KiCad GUI is still missing some German items I did not include localized screen shots.

### CODE REVIEW

**Comment by nickoe** [comment]
I suspect this is against the product branch, right?

What is the status against kicad 4.0.2?

**Comment by nickoe** [comment]
Stupid question, I confused myself there....

**Comment by ciampix** [comment]
If it is just a .po file update matter, I can do it for you. Just let me know if you want me to update the German .po (for the KiCad program, not the manual of course...) file for you...

**Comment by transistorgrab** [comment]
@ciampix No I think it is something else. I created the mo file for KiCad by hand from the 4.0 branch of KiCad/kicad-i18n. After pulling the po file, running it through poedit to generate the mo file and putting this generated file in the appropriate folder on my computer the passage translated in the po file do not show up in the KiCad GUI. I did not file a bug report for this yet, but it is visible in KiCad 4.0.2 on Ubuntu as well as in KiCad 4.0.1 on Windows.

**Pull request merged**
