### PR TITLE
Add accelerator keys and hotkeys to GSIK

### PR DESCRIPTION
**Pull request by evanshultz**
See the comments below. A bit of discussion is needed before merging this path.

### CODE REVIEW

**Comment by evanshultz** [comment]
Oops. Apologies if this is my fault. I thought pull requests wouldn't be built unless they were merged??

**Comment by kinichiro** [comment]
Hi,

You need a blank line before `image::`, like below.
<pre>
...
Accelerator keys are shown on the right side of all menu panes:

image::images/gsik_accelerator_keys.png[Accelerator keys]

=== Hotkeys
A hotkey is equal to an accelerator key plus a left mouse click. Using a
hotkey starts the command immediately at the current cursor location. Use
a hotkey to quickly change commands without interrupting your workflow.

To view hotkeys within any KiCad tool go to *_Preferences -> Hotkeys ->
List Current Keys_* or press the question mark ("?"):

image::images/gsik_hotkeys.png[Hotkeys]

You can edit the assignment of hotkeys, and import or export them, from the
...
</pre>

Please will you fix above issues on your patch-8 branch,
and push here again ?

Now, pull requests are tested by travis-ci to prevent breaking build after merge.

Best Regards,

**Comment by evanshultz** [comment]
Thanks for letting me know, sorry for the error. And special thanks for seeing how confusing the keys can be and writing the text for it!

**Comment by ciampix** [comment]
Thanks!

**Pull request merged**
