### PR TITLE
Adding COMPONENT for installation.

### PR DESCRIPTION
**Pull request by jsreynaud**
Available components are <format>-<language> with:
<format> in html, pdf and epub
and
<language> in en, fr, de, ja...

### CODE REVIEW

**Comment by nickoe** [comment]
retest this please

**Comment by nickoe** [comment]
FYI the jenkins job was misconfigured from the repo move to the kicad org and the lowercase rename. It should be fixed now.

**Comment by nickoe** [comment]
retest this please

**Comment by nickoe** [comment]
I don't quite understand the cmake component, what exactly does it do? I don't see new make targets being made.

**Comment by jsreynaud** [comment]
It allow package manager to make partial installation of a specific piece of the project.
For example if you want to install at a different place english files and french files (for packaging): 
http://www.cmake.org/Wiki/CMake:Component_Install_With_CPack

**Comment by nickoe** [comment]
Ok, I i see.

**Pull request merged**
