### PR TITLE
Gsik eeschema label wrong placement in image 2

### PR DESCRIPTION
**Pull request by EeliK**

### CODE REVIEW

**Comment by EeliK** [comment]
Bump

**Comment by ciampix** [comment]
Sorry I am not a native English speaker, what do you mean with "bump"?

**Comment by keruseykaryu** [comment]
He want to push this PR to the top of the list.

**Comment by EeliK** [comment]
https://www.webopedia.com/TERM/T/thread_bump.html

Because this hasn't been merged yet, I thought it may have been forgotten.

Eeli Kaikkonen

la 12. tammik. 2019 klo 20.59 Marco Ciampa (notifications@github.com)
kirjoitti:

**Comment by ciampix** [comment]
Thank you all for the care, for the patch and for the explanation!

**Pull request merged**
