### PR TITLE
Add description and image of manual routing

### PR DESCRIPTION
**Pull request by johnbeard**

### CODE REVIEW

**Comment by kinichiro** [comment]
Hi,
I don't think src/pcbnew/images/Pcbnew_routing_posture.svg file is needed.
Only src/pcbnew/images/Pcbnew_routing_posture.png is used to build document.

**Comment by johnbeard** [comment]
The SVG is the original source of the image - the PNG is just the render. That way if someone wants to modify the image, they dont have to re-draw the SVG? The other vector graphics for the staggering diagrams are done in the same way.

**Comment by nickoe** [comment]
This looks good to me.

**Comment by ciampix** [comment]
Very good!

**Pull request merged**
