### PR TITLE
Eeschema french translation completed : chapter 14

### PR DESCRIPTION
**Pull request by MarcusFecit**
BTW, Marco, if you could settle an empty kicad/fr.po in the srcs, it'll be the next..
Thanks !

### CODE REVIEW

**Comment by ciampix** [comment]
Great, thanks!

**Comment by ciampix** [comment]
Added the French template for KiCad project manager just now...

**Comment by MarcusFecit** [comment]
Le 05/01/2016 17:52, Marco Ciampa a écrit :
>
> Added the French template for KiCad project manager just now...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KiCad/kicad-doc/pull/266#issuecomment-169059032>.
>

OK, I noticed.

You can safely delete my #267 pull-request..

Thanks

-- 
Marc

**Comment by kinichiro** [comment]
Hi,  @MarcusFecit 

I think that src/eeschema/po/fr.po has 2 issues.

(1)  missing escape '\'

Now, I got error when I tried to update po file of eeschema French version.
<pre>
$ cd kicad-doc/src/eeschema/
$ touch *.adoc
$ make -f ../../utils/old-build-scripts/Makefile po/fr.po
...
Updating po/fr.po:
po/fr.po:4831:55: invalid control sequence
msgmerge: found 1 fatal error
Error while running msgmerge:
../../utils/old-build-scripts/Makefile:93: recipe for target 'po/fr.po' failed
make: *** [po/fr.po] Error 1
</pre>

Line 4831 of src/eeschema/po/fr.po is like this.
<pre>
   4831 "Windows et que tous les fichiers sont situes dans F:\kicad\bin."
</pre>
I think '\' should be escaped one more '\'.
<pre>
   4831 "Windows et que tous les fichiers sont situes dans F:\\kicad\\bin."
</pre>


(2) 'msgid' and 'msgstr' entries do not both end with '\n'

It seems that some numbers of '\n' between 'msgid' and 'msgstr' are different in eeschema/po/fr.po, too.
<pre>
Updating po/fr.po:
............................................................................................................................................... done.
po/fr.po:3956: 'msgid' and 'msgstr' entries do not both end with '\n'
po/fr.po:3964: 'msgid' and 'msgstr' entries do not both end with '\n'
msgfmt: found 2 fatal errors
po/fr.po: 1183 translated messages, 10 fuzzy translations, 224 untranslated messages.
</pre>

Could you fix these issues, too ?
Best Regards,

**Comment by ciampix** [comment]
Fixed

**Pull request merged**
