### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by baranovskiykonstantin**
```
Scanning dependencies of target pcbnew_updatepo_ru
Parse input files... 
pcbnew_create_and_modify_board.adoc:172: It seems that you are adding unindented content to an item.
The "standard" allows this, but you may still want to fix your document.
pcbnew_creating_editing_footprints.adoc:407: It seems that you are adding unindented content to an item.
The "standard" allows this, but you may still want to fix your document.
pcbnew_creating_editing_footprints.adoc:410: It seems that you are adding unindented content to an item.
The "standard" allows this, but you may still want to fix your document.
pcbnew_creating_editing_footprints.adoc:412: It seems that you are adding unindented content to an item.
The "standard" allows this, but you may still want to fix your document.
pcbnew_creating_editing_footprints.adoc:413: It seems that you are adding unindented content to an item.
The "standard" allows this, but you may still want to fix your document.
pcbnew_installation.adoc:145: It seems that you are adding unindented content to an item.
The "standard" allows this, but you may still want to fix your document.
pcbnew_installation.adoc:146: It seems that you are adding unindented content to an item.
The "standard" allows this, but you may still want to fix your document.
pcbnew_installation.adoc:148: It seems that you are adding unindented content to an item.
The "standard" allows this, but you may still want to fix your document.
done.
Updating po/ru.po:
....................................................................................................................................................... done.
```

### CODE REVIEW

**Comment by tijuca** [comment]
The fix is fine, but could the subject of the commit message please a bit improved?

Subject lines shouldn't be longer than 50 characters, but definitely not longer than about 72-78 characters.
And some description why this changes was needed helps later if someone is going through the various commits and tries to understand why this change was needed.

https://chris.beams.io/posts/git-commit/

**Comment by baranovskiykonstantin** [comment]
Subject fixed.

**Comment by tijuca** [comment]
Thanks, this is better. But now you have lines in the body that are clearly larger than 80 characters for non code parts.

What about:

> Correct various indentation of numbered lists
> 
> Asciidoc allows of course the usage of numbered lists [1].  Due some
> line breaks of long items within the source without a indentation of any
> text line after a line break the asciidoc processor is showing a warning
> message like this: 
> 
>  ---%<---
>  pcbnew_create_and_modify_board.adoc:172: It seems that you are adding unindented content to an item.
>  The "standard" allows this, but you may still want to fix your document.
>  --->%---
> 
> It's possible that such warnings can be moved to a error later in future
> versions of asciidoc. The warning is easy solvable, we just need to
> intend the following lines. This change fixes the warnings of the
> asciidoc processor but also increases the readability of the *.adoc
> files a bit.
> 
> [1] http://asciidoctor.org/docs/asciidoc-writers-guide/#ordering-the-things
>

**Comment by baranovskiykonstantin** [comment]
OMG

**Comment by ciampix** [comment]
For me it is fine... if anyone has no complains I am going to commit it.

**Comment by tijuca** [comment]
There will nobody complaining more as there is no other review process as the one done by the people with administrative access to this repository. This is one of the really annoying downsides of this GitHub workflow.

For me as someone who also working on other more QS driven repos this is something I really dislike but I need to live with this. Writing useful commit messages is a thing that makes real sense if you work on more than one or bigger repositories.

**Comment by ciampix** [comment]
@tijuca I see your point, any suggestion for a better service?

**Comment by tijuca** [comment]
Well, partially I take a look into such pull requests, but not generally, I simply have not enough time for doing this regularly. If I see something that should be done better (and I have time and the mood to write something useful) I will "complain" about. But to clone other repositories and write own pull requests about more lightweight things like commit messages I wont start as this is a wast of energy in my eyes.

I have no big master plan for solving such problems and issues, I guess that things like the desired style of commit messages or coding style is a thing that needs to be clear within a community of contributors. Most of the other projects I know have rule set of what the project is expecting from contributors. And one thing I always see in such projects is a file that is describing how a contributor should act and how commits needs to look like. This part is completely missing from [README.adoc](https://github.com/KiCad/kicad-doc/blob/master/README.adoc).

For libcoap we have added a longer file [CONTRIBUTE](https://github.com/obgm/libcoap/blob/develop/CONTRIBUTE) with a extra section about patches and commits and all other hopefully useful informations. This helps the project team to point users and contributors in case of typical raised questions to the related answers and information. So what about to do something similar for kicad-doc? We probably don't need a big chapter on that, but some few lines in the README.adoc should be added I think. I'm short on time for doing a proposal so don't count much on me to see a enhancement in the next days.

Back to the importance of a commit message, I'm not "the" project kicad-doc, I just can try to point out how important a good commit message is. For me is a commit message, especially a subject with the information `bugfix commit` or `I have fixed a problem about 'error happen in basic modul' and also done some fixup of spellings  in component  foo after indentation clean up` a real pain. It's take me a lot of time to see and understand what was changed. Over the time I have understand a good commit messages can be a major improvement and motivation for contributors! But it's up to the administrative people to enforce and promote such a behaviour.

The above examples of subjects lines are of course not really true for the kiacd-doc tree as the nature of this repository is a bit different to other source code related git trees. But why should we do here something different and more bad as in other projects that do classical source code work?

I won't write about why this is all important, there are a ton of websites and blogs about that out there, here are some (old) links that still are relevant after all that years.

https://wildbit.com/blog/2008/11/11/the-importance-of-commit-messages
http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
http://lbrandy.com/blog/2009/03/writing-better-commit-messages/
http://who-t.blogspot.de/2009/12/on-commit-messages.html
http://www.denx.de/wiki/U-Boot/Patches

**Comment by baranovskiykonstantin** [comment]
Anything else wrong with the pull request?

**Comment by tijuca** [comment]
As I've seen the Travis check was successful so no, there is now nothing technically wrong with this PR. Thank you very much for following my suggestions!

**Comment by ciampix** [comment]
Thanks!

**Comment by ciampix** [comment]
Are there similar issues in the master branch? If so, would you mind fix those also? TIA!

**Comment by tijuca** [comment]
Isn't this PR about merging into master? Or do you mean the branch 4.0? In case of the latter I think this can be ignored as long as there is no planned KiCad release 4.0.8.

**Comment by ciampix** [comment]
Yes sorry I mixmatched the master with the 4.0 branch ... sorry for the noise

**Pull request merged**
