### PR TITLE
 Russian translation of PCB Calculator

### PR DESCRIPTION
**Pull request by baranovskiykonstantin**

### CODE REVIEW

**Comment by nickoe** [comment]
@baranovskiykonstantin What is the reasoning about replacing the Ω with Ohm?

**Comment by baranovskiykonstantin** [comment]
@nickoe I niticed it in commit message.

**Comment by nickoe** [comment]
Hmm, ok, I missed that one.

**Comment by nickoe** [comment]
Built failed because of https://github.com/KiCad/kicad-doc/issues/688

**Pull request merged**
