### PR TITLE
Fix some error for lang-zh.conf

### PR DESCRIPTION
**Pull request by taotieren**
Fix some error for lang-zh.conf

### CODE REVIEW

**Comment by ciampix** [comment]
Please separate the two files...

**Comment by nickoe** [comment]
@ciampix, what do you mean? Each file to two commit?

**Comment by ciampix** [comment]
I mean every commit should not have any conflict. I can approve a commit for file. If one file diff has a problem and the other not, why not commit all those that have no problems and then separately fix the problematic ones? What I would like to avoid is to manually fix every commit that has a problem (if possible). Obviously I can fix it but: 1) if I fix it, the user miss an occasion to learn something and 2) I won't be really sure of the results, since I am afraid I do not know Chinese and I can make mistakes...

**Comment by taotieren** [comment]
Sorry，I want to test the src/idf_exporter/po/zh.po file is not fixed correctly.

**Comment by taotieren** [comment]
[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=622359;msg=15](url)

**Comment by taotieren** [comment]
There are Chinese Simplified Form (zh_CN) and Chinese Traditional Form (zh_TW) in Chinese. I use Chinese Simplified Form (zh_CN). Chinese translation in kicad-doc is also using Chinese Simplified Form (zh_CN). Can zh.po be updated to zh_CN.po?

**Comment by taotieren** [comment]
Simplified Chinese(zh_CN) and Traditional Chinese(zh_TW) have different vocabulary and usage.

**Comment by ciampix** [comment]
Thanks, I'll rename the file too...

**Comment by ciampix** [comment]
You didn't look at #639? Do you? ;-)

**Comment by taotieren** [comment]
No,I look,Add Single and double quotation marks for lang-zh.conf

**Comment by ciampix** [comment]
Good, thanks. I picked it up that somewhere in the Internet but obviously I was not sure about it's correctness. In a few minutes I'll have it renamed and I'll close all PR related...
I think you can also try to propose the inclusion of that .conf file to the main asciidoc devs so as to have it automatically included in the next asciidoc version...

**Comment by ciampix** [comment]
In your opinion, should we rename all references to zh to zh_CN? I mean, also all the .po files?

**Comment by taotieren** [comment]
Because of China's national conditions, there are two kinds of Chinese, simplified Chinese(zh_CN) and traditional Chinese(zh_TW). At present, all zh.po are simplified Chinese(zh_CN) and can be changed to zh_CN.po.

**Comment by ciampix** [comment]
Yes they can be changed but in your opinion they should? This is a question, I am asking you because I do not know...
 Anyway it is wise to leave it as it is now for the time being (this KiCad version 5.2) since I've seen that cmake scripts do not work with aa_BB type of .po files...

**Comment by taotieren** [comment]
Thanks,I hope to improve this problem in the future.

**Comment by evanshultz** [comment]
@ciampix 
Yes, they should be changed. It's totally ambiguous to not clarify if the translation is Traditional or Simplified Chinese. I took a quick look at https://github.com/KiCad/kicad-doc/blob/master/src/eeschema/po/zh.po, as an example, and the characters are simplified. Our translation should reflect that and leave room for a traditional translation, should one ever be added.

**Comment by ciampix** [comment]
I agree but my knowledge of cmake is near zero. If you change all files from zh to zh_CN cmake will fail ... see  #672 ...

**Comment by evanshultz** [comment]
I understand and I saw that. I'm only answering your question above.

I don't know cmake either.

**Pull request merged**
