### PR TITLE
Russian translation update (Getting started in kicad)

### PR DESCRIPTION
**Pull request by yurayko**

### CODE REVIEW

**Comment by kinichiro** [comment]
@yurayko How about add your credit in src/getting_started_in_kicad/po/addendum.ru ?

**Comment by baranovskiykonstantin** [comment]
@yurayko thank you for your contribution in Russian translation. If your have time and possibility to give more, please join to us to discussion of the translation, here:
http://electronix.ru/forum/index.php?showtopic=126971&view=findpost&p=1418041

**Comment by ciampix** [comment]
Thanks!

**Comment by yurayko** [comment]
Konstantin, Ok.
kinichiro, when a document will be done (may be).

**Pull request merged**
