### PR TITLE
Update Japanese Translation

### PR DESCRIPTION
**Pull request by starfort-jp**
GSiK : updated Japanese translation (completed, so far)

### CODE REVIEW

**Comment by ciampix** [comment]
Hi @starfort-jp 
you added a (transparent) spurious char at the start of the addendum file. Please delete it to allow the compilation, thanks!

**Comment by starfort-jp** [comment]
Hi @ciampix 
I'm sorry for my mistake.  I deleted otiose BOM in the addendum file.  Please check it out.
Thank you.

**Comment by ciampix** [comment]
No problem at all... it was an invisible char...thank you for the translation and prompt feedback!

**Comment by starfort-jp** [comment]
Thanks again.

**Pull request merged**
