### PR TITLE
Add description about gerber file extensions (GSiK)

### PR DESCRIPTION
**Pull request by kinichiro**
refer to https://github.com/KiCad/kicad-doc/pull/162#issuecomment-148920315

### CODE REVIEW

**Comment by kinichiro** [comment]
Could you check and if OK, merge this please . thank you.
http://ci.kicad-pcb.org/job/kicad-doc-testing-pull-request/180/artifact/build-cmake/src/getting_started_in_kicad/en/getting_started_in_kicad.html#generate-gerber-files

**Comment by kinichiro** [comment]
@nickoe I think this PR could be merged.
Could you take a look this, please ?

**Comment by ciampix** [comment]
Formally it is ok ... I have no experiences in Protel, @nickoe ?

**Comment by nickoe** [comment]
@ciampix The table does not illustrate the back silk, hence no .gbo file.

@kinichiro Thank your for your suggestions, but I looked into it again today. Some thoughts; maybe we should put the that table under a heading which says protel file extensions such that it is more obvious that there is some (option) called protel file extensions.

I think the (ex <old_name>) scheme is a bad way to describe the old names. Maybe just make a new column with legacy layer names?

Someone mentioned that about "when you Plot with *use protel* checked", that _checked_ just sounds wrong. I guess a better wording is _enabled_.

What do you think?

**Comment by kinichiro** [comment]
@ciampix I think you only 4 Layers enabled in the Plot dialog. No ?

@nickoe I agree with "old name should be separeted", and "enabled sounds good".
Let me share your image. How about this table below ?
And I feel if this table header is used, we don't need "NOTE" block any more.

BTW, should we add back silk in the table ? 
(If so, tell me the old back silk layer name, "SilkS_Cop" ?)

...
3. These are the layers you need to select for making a typical 2-layer PCB:

KiCad Layer Name |Old Layer Name |What it is |Default Gerber Extension |"Use Protel filename extensions" is enabled
-----------------|---------------|-----------|-------------------------|-------------------------------------------
B.Cu |Copper |Bottom Layer |.GBR |.GBL
F.Cu |Component |Top Layer |.GBR |.GTL
F.SilkS |SilkS_Cmp |Top Overlay |.GBR |.GTO
B.Mask |Mask_Cop |Bottom Solder Resist |.GBR |.GBS
F.Mask |Mask_Cmp |Top Solder Resist |.GBR |.GTS
Edge.Cuts |Edges_Pcb |Edges |.GBR |.GM1

~~NOTE:~~
~~The Protel File Extensions in the table above are used when the~~
~~"Use Protel filename extensions" in the Plot dialog is enabled.~~
~~If this option is disabled, all the gerber files are generated~~
~~with the extension .GBR.~~
...

**Comment by nickoe** [comment]
Looks better. Maybe rename "What it is" to just "Layer" and put it as the first column on the left.

**Comment by kinichiro** [comment]
better ? not best ? :-) Take a look at update version below.

...
3. These are the layers you need to select for making a typical 2-layer PCB:

Layer |KiCad Layer Name |Old Layer Name |Default Gerber Extension |"Use Protel filename extensions" is enabled
-----------------|---------------|-----------|-------------------------|-------------------------------------------
Bottom Layer |B.Cu |Copper |.GBR |.GBL
Top Layer |F.Cu |Component |.GBR |.GTL
Top Overlay |F.SilkS |SilkS_Cmp |.GBR |.GTO
Bottom Solder Resist |B.Mask |Mask_Cop |.GBR |.GBS
Top Solder Resist |F.Mask |Mask_Cmp |.GBR |.GTS
Edges |Edge.Cuts |Edges_Pcb |.GBR |.GM1

~~NOTE:~~
~~The Protel File Extensions in the table above are used when the~~
~~"Use Protel filename extensions" in the Plot dialog is enabled.~~
~~If this option is disabled, all the gerber files are generated~~
~~with the extension .GBR.~~
...

**Comment by nickoe** [comment]
Yeah, I think it is way better. I have yet to see how that looks in the real docs, but I think it will be fine. Please prepare a pull request, then we should be able to see it on the pull request builder.

**Comment by kinichiro** [comment]
@nickoe OK, I updated the PR. Verify from here, please.
http://ci.kicad-pcb.org/job/kicad-doc-testing-pull-request/183/artifact/build-cmake/src/getting_started_in_kicad/en/getting_started_in_kicad.html#generate-gerber-files

Any comments are appreciated.
Thanks.

**Comment by nickoe** [comment]
Thank you very much. It looks fine for me, so I will merge it.

**Pull request merged**
