### PR TITLE
Update ja 151021

### PR DESCRIPTION
**Pull request by yoneken**
kicad.jp team translated manuals in Japanese.

### CODE REVIEW

**Comment by ciampix** [comment]
retest this please

**Comment by yoneken** [comment]
@ciampix sorry, I had missed 5 commits. Now, I added them and confirmed the success to build with no issue.

**Comment by ciampix** [comment]
@yoneken I was trying to pass a command to Jenkins CI (if I correctly understand how it works): "retest this please" should be read & executed by Jenkins CI... then I will merge safely, ok?

**Comment by ciampix** [comment]
Thanks!

**Comment by yoneken** [comment]
@ciampix Thank you so much!!

**Pull request merged**
