### PR TITLE
Updated es.po to 4.0.5

### PR DESCRIPTION
**Pull request by ElektroQuark**

### CODE REVIEW

**Comment by kinichiro** [comment]
@ElektroQuark This PR is targeted to `master` branch.
`master` is development branch for docs, and `4.0` is stable branch.
Could you post PR to `4.0` branch, please ?

**Comment by ElektroQuark** [comment]
Sorry, too much work...

**Comment by kinichiro** [comment]
@ElektroQuark May I merge this, too ?
If I merge this PR, `master` branch translation will be update.
OK ?

**Comment by ElektroQuark** [comment]
OK. Thanks El 13 dic. 2016 2:40 p. m., kinichiro inoguchi <notifications@github.com> escribió:@ElektroQuark May I merge this, too ?
If I merge this PR, master branch translation will be update.
OK ?

**Comment by ElektroQuark** [comment]
@kinichiro 
Yes, merge it please.
Thank you.

**Comment by kinichiro** [comment]
I will close this PR to master branch since po file was not updated.

**Pull request closed without merging**
