### PR TITLE
Start translation of Pcbnew to German, add Style definitions for writing style policy

### PR DESCRIPTION
**Pull request by transistorgrab**
definitions in writing style policy are meant for discussion. It should definitely be synced with the current style in use where applicable. I tried that and built a small html with css to get a feel for the result. I'm not quite sure what can be done with asciidoc.
I think it should be thorough to make it possible to know what is expected to see when it is rendered.

### CODE REVIEW

**Comment by ciampix** [comment]
1) Please create separate the translation from the writing style policy
2) rebase: your branch cannot be merged, there are some conflicts

**Comment by tijuca** [comment]
Some suggestions for better readability and understanding of the single commits:
Please avoid merge commits from current upstream, use rebase and separate branch(es) instead.
```
# your are on branch master
git checkout -b your_branch # create a new branch from the current branch, even with changes on the index
... work on your branch
git commit foo
```
Nothing new until here. Now you want to update your_branch on remote master and put your commits on top of that.
```
git checkout master # going back to the master branch
git pull remote_name master # substitute $remote_name with the name you have choosen
git checkout your_branch
git rebase master
```
some more reflections on merge vs. rebase can found here
* http://stackoverflow.com/questions/804115/when-do-you-use-git-rebase-instead-of-git-merge
* https://git-scm.com/book/en/v2/Git-Branching-Rebasing

If you really want to work on master (which is quite often a bad idea on the long term) you can use the option <code>--rebase</code> while pulling the latest upstream changes. <code>git pull remote_name master --rebase</code>. This setting is the default on new git versions.

**Comment by transistorgrab** [comment]
I think the main problem with the current pull request is that the file was renamed. I'm not a software developer, so I'm not quite so familiar with git. Thanks for the suggestions, will try that approach further on.

**Comment by tijuca** [comment]
Feel free to contact me if you have questions. My email address will be found within my commits.
Git can be frustrating in the beginning if you do it the "wrong" way.

**Comment by transistorgrab** [comment]
Ok, whats the suggestion for the current pull request? How can we solve the conflict which results from a renamed file. can this be done manually for this time? How do I proceed when the conflict is solved? When I pull in the changes, is the file then renamed for my local repository too? (I expect so.)
After this I will see how to move my changes to files to separate branches.

**Comment by ciampix** [comment]
I can do it all for you but ... if I do it:
1) you never learn
2) next time will be the same
3) probably learning how to do it well is useful for you

Having said this, the easiest (and dumb) way to resolve this is to create another clone of the main trunk, apply your modifications manually and ask for a pull. The same for the different topic mods. After having done this you can safely drop your current branch and I will close this PR.
Next time the best way is to "rebase" and before doing this I suggest you to read carefully what @tijuca (thanks) suggested to you.

Feel free to ask any question, thanks!

**Comment by transistorgrab** [comment]
tried a rebase, hoping it works... :)

**Pull request closed without merging**
