### PR TITLE
Kicad french PNGs

### PR DESCRIPTION
**Pull request by MarcusFecit**

### CODE REVIEW

**Comment by kinichiro** [comment]
Is this PR related with #269 ?
PR #269 seems to use images of this PR.

**Comment by ciampix** [comment]
Yes I see that this commit is filling in the holes in last French translation... I think he forgot the images that now is adding... anyway compilation gone right this time...

**Comment by MarcusFecit** [comment]
Le 06/01/2016 18:23, kinichiro inoguchi a écrit :
>
> Is this PR related with #269
> <https://github.com/KiCad/kicad-doc/pull/269> ?
> PR #269 <https://github.com/KiCad/kicad-doc/pull/269> seems to use
> images of this PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KiCad/kicad-doc/pull/271#issuecomment-169395039>.
>

I put the images in my build/src directory instead of kicad-doc/src and
it does compile without errors or warnings

But i noticed later they haven't been commited with the french translations

PR #271 corrects my mistake and adds more images

Sorry for the noise

-- 
Marc Berlioux

**Comment by kinichiro** [comment]
I see.
Thanks for your explanation.

**Pull request merged**
